### ISSUE TITLE
Unable to access the google driver link to download datasets

### ISSUE THREAD

**Issue by hujingtao** [squareRoot3/GADBench#2]
Hello, is there anything wrong with the Google driver link? I cannot fetch the datasets on it.
Or can you provide a Baidu Netdisk link for convenience?
Thanks a lot.

**Comment by squareRoot3** [comment]
I have checked it. The link works well. I will provide a Baidu Netdisk link soon.

**Comment by squareRoot3** [comment]
https://pan.baidu.com/s/1-RQJRzML3B2Ol7H9N_M4CA
jx2k

**Comment by hujingtao** [comment]
> https://pan.baidu.com/s/1-RQJRzML3B2Ol7H9N_M4CA jx2k

I really appreciate your help  =)
