### ISSUE TITLE
数据集划分的问题

### ISSUE THREAD

**Issue by Djerry-h** [squareRoot3/GADBench#3]
您好，我想请问，代码中关于半监督的数据集划分是按照什么样的比例划分的？

**Comment by squareRoot3** [comment]
您好, 论文里有介绍.  To more accurately mimic real-world semi-supervised scenarios, we standardize the training set across all datasets to include a total of 100 labels—20 positive labels (anomalous nodes) and 80 negative labels (normal nodes). To ensure robustness in our findings, we execute ten random splits on each dataset and analyze the average performance of the model.

**Comment by Djerry-h** [comment]
> 您好, 论文里有介绍. To more accurately mimic real-world semi-supervised scenarios, we standardize the training set across all datasets to include a total of 100 labels—20 positive labels (anomalous nodes) and 80 negative labels (normal nodes). To ensure robustness in our findings, we execute ten random splits on each dataset and analyze the average performance of the model.

在代码中具体是哪一部分呀，我没有找到？

**Comment by squareRoot3** [comment]
数据集已经预处理好了 预处理脚本在preprocess.ipynb
```
            pos_index = np.where(labels == 1)[0]
            neg_index = list(set(index) - set(pos_index))
            pos_train_idx = np.random.choice(pos_index, size=2*samples, replace=False)
            neg_train_idx = np.random.choice(neg_index, size=8*samples, replace=False)
            train_idx = np.concatenate([pos_train_idx[:samples], neg_train_idx[:4*samples]])
            train_masks[train_idx, 10+i] = 1
            val_idx = np.concatenate([pos_train_idx[samples:], neg_train_idx[4*samples:]])
            val_masks[val_idx, 10+i] = 1
            test_masks[index, 10+i] = 1
            test_masks[train_idx, 10+i] = 0
            test_masks[val_idx, 10+i] = 0
```

**Comment by Djerry-h** [comment]
> 数据集已经预处理好了 预处理脚本在preprocess.ipynb
> 
> ```
>             pos_index = np.where(labels == 1)[0]
>             neg_index = list(set(index) - set(pos_index))
>             pos_train_idx = np.random.choice(pos_index, size=2*samples, replace=False)
>             neg_train_idx = np.random.choice(neg_index, size=8*samples, replace=False)
>             train_idx = np.concatenate([pos_train_idx[:samples], neg_train_idx[:4*samples]])
>             train_masks[train_idx, 10+i] = 1
>             val_idx = np.concatenate([pos_train_idx[samples:], neg_train_idx[4*samples:]])
>             val_masks[val_idx, 10+i] = 1
>             test_masks[index, 10+i] = 1
>             test_masks[train_idx, 10+i] = 0
>             test_masks[val_idx, 10+i] = 0
> ```

感谢您的回信，谢谢
