### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by fatalite1** [squareRoot3/GADBench#4]
为什么论文中展示的图的边的数量跟打印出来的下载的数据集的边数量不一样？比如questions数据集，打印出来是：
![image](https://github.com/squareRoot3/GADBench/assets/61609576/63616626-c23a-46d8-8ce8-3cbd2c09ef29)
但是论文中是：
![image](https://github.com/squareRoot3/GADBench/assets/61609576/e101e5de-11ad-4722-8a77-bc6eecb9f03a)

**Comment by squareRoot3** [comment]
您好! 这是因为代码中的数据集已经进行了预处理，包括添加反向边和自环等。而论文中边的数量来自于原始数据。

**Comment by fatalite1** [comment]
> 您好! 这是因为代码中的数据集已经进行了预处理，包括添加反向边和自环等。而论文中边的数量来自于原始数据。

好的，谢谢您。顺便问一下添加反向边是为了把图变成无向图，那为什么要添加自环呢？

**Comment by squareRoot3** [comment]
这是一个好问题！添加自环一方面是防止数据集里有度数为0的节点，另一方面是多数图神经网络（例如GCN/GAT）添加自环能够提升效果。这里算是采用了偷懒的做法，更好的做法应该视数据集、模型的具体情况而定。

**Comment by fatalite1** [comment]
> 这是一个好问题！添加自环一方面是防止数据集里有度数为0的节点，另一方面是多数图神经网络（例如GCN/GAT）添加自环能够提升效果。这里算是采用了偷懒的做法，更好的做法应该视数据集、模型的具体情况而定。

好的了解了，谢谢您
