### ISSUE TITLE
请问半监督情况下各个算法是怎样工作的？

### ISSUE THREAD

**Issue by chzhao01** [squareRoot3/GADBench#5]
如题。比如训练集里有labeled data 与 unlabled data ，是怎么综合利用两类数据的信息的？

**Comment by squareRoot3** [comment]
半监督时依旧仅通过 label 进行训练, 具体可以看每个模型 loss 的计算

**Comment by chzhao01** [comment]
您好，我想再追问一下，您论文里的半监督是怎么体现的呢？我感觉您代码里的半监督设定也是根据一个较小的trainset进行训练，没有理解到半监督的含义（没有冒犯的意思，确实没看懂）

**Comment by squareRoot3** [comment]
根据一个较小的trainset进行训练, 确实说成 weakly-supervised或 few-shot 会更好理解些, 但 semi-supervised也是 GNN 里比较常见的说法, 具体可以参考Semi-Supervised Classification with Graph Convolutional Networks里的阐述.

**Comment by squareRoot3** [comment]
从我的理解, 这里的 semi 是指GNN 训练时, 少数的label通过图结构可以辐射更多的无标签节点

**Comment by chzhao01** [comment]
谢谢您的回复。我可以这样理解吗：
所以在您的论文里，对于每个算法，监督学习与半监督学习区别在于training set 比例的不同，比如监督学习中trainingset为40%，在半监督中为1%或者像您的论文里设置了100个labels。而算法的工作流程是一样的。这种semi or fully-supervised 的setting是GNN里的常见做法。

**Comment by squareRoot3** [comment]
是的

**Comment by chzhao01** [comment]
好的，谢谢回复！
